### ISSUE TITLE
Is it possible to port this library to be used by the Visual Studio compiler (MSVC)?

### ISSUE THREAD

**Issue by a-rabin** [Water-Melon/Melon#7]
Title.

**Comment by Water-Melon** [comment]
It is not supported yet, but it may be ported to MSVC in the future. However, in Windows, this framework is not supported for the time being.
I'm not familiar with MSVC, so it may take a long time. It is free to fork and modify Melon, and submit PRs if you would like to contribute and join in this project. That would be very grateful.

**Comment by a-rabin** [comment]
I see. Thank you for your reply.

**Comment by Water-Melon** [comment]
Hello,

Currently, support for `Mingw` and `MSYS2` has been added on Windows.

In the short term, there won't be consideration for `MSVC` support because of the inconsistent level of support for certain macro features by the compiler. This inconsistency results in a substantial amount of work and would complicate the codebase.

Hence, we'll temporarily close this issue. It will be reopened when support for MSVC is on to the schedule
